[build]
  base = "client"
  command = "CI=false npm run build"
  publish = "build"
  ignore = "git diff --quiet HEAD^ HEAD -- ../client/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200